# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: konpeko.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="konpeko.proto",
    package="konpeko",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\rkonpeko.proto\x12\x07konpeko"\x1c\n\x0cGreetRequest\x12\x0c\n\x04name\x18\x01 \x01(\t"\x1d\n\nGreetReply\x12\x0f\n\x07message\x18\x01 \x01(\t2F\n\x06Pekora\x12<\n\x0cIdolGreeting\x12\x15.konpeko.GreetRequest\x1a\x13.konpeko.GreetReply"\x00\x62\x06proto3',
)


_GREETREQUEST = _descriptor.Descriptor(
    name="GreetRequest",
    full_name="konpeko.GreetRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="name",
            full_name="konpeko.GreetRequest.name",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=26,
    serialized_end=54,
)


_GREETREPLY = _descriptor.Descriptor(
    name="GreetReply",
    full_name="konpeko.GreetReply",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="message",
            full_name="konpeko.GreetReply.message",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=56,
    serialized_end=85,
)

DESCRIPTOR.message_types_by_name["GreetRequest"] = _GREETREQUEST
DESCRIPTOR.message_types_by_name["GreetReply"] = _GREETREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GreetRequest = _reflection.GeneratedProtocolMessageType(
    "GreetRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _GREETREQUEST,
        "__module__": "konpeko_pb2"
        # @@protoc_insertion_point(class_scope:konpeko.GreetRequest)
    },
)
_sym_db.RegisterMessage(GreetRequest)

GreetReply = _reflection.GeneratedProtocolMessageType(
    "GreetReply",
    (_message.Message,),
    {
        "DESCRIPTOR": _GREETREPLY,
        "__module__": "konpeko_pb2"
        # @@protoc_insertion_point(class_scope:konpeko.GreetReply)
    },
)
_sym_db.RegisterMessage(GreetReply)


_PEKORA = _descriptor.ServiceDescriptor(
    name="Pekora",
    full_name="konpeko.Pekora",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=87,
    serialized_end=157,
    methods=[
        _descriptor.MethodDescriptor(
            name="IdolGreeting",
            full_name="konpeko.Pekora.IdolGreeting",
            index=0,
            containing_service=None,
            input_type=_GREETREQUEST,
            output_type=_GREETREPLY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_PEKORA)

DESCRIPTOR.services_by_name["Pekora"] = _PEKORA

# @@protoc_insertion_point(module_scope)
