# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import konpeko_pb2 as konpeko__pb2


class PekoraStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IdolGreeting = channel.unary_unary(
            "/konpeko.Pekora/IdolGreeting",
            request_serializer=konpeko__pb2.GreetRequest.SerializeToString,
            response_deserializer=konpeko__pb2.GreetReply.FromString,
        )


class PekoraServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IdolGreeting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_PekoraServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "IdolGreeting": grpc.unary_unary_rpc_method_handler(
            servicer.IdolGreeting,
            request_deserializer=konpeko__pb2.GreetRequest.FromString,
            response_serializer=konpeko__pb2.GreetReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "konpeko.Pekora", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Pekora(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IdolGreeting(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/konpeko.Pekora/IdolGreeting",
            konpeko__pb2.GreetRequest.SerializeToString,
            konpeko__pb2.GreetReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
